# Setup
title:        Aidan Kinzett
tagline:      "some guy"
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Aidan Kinzett
  url:        "http://aidankinzett.com"

# Gems
gems:
  - jekyll-paginate
  - jemoji

#Others
markdown: kramdown

#Dumb stuff
emojiArray:
    - "ğŸ˜"
    - "ğŸ˜Š"
    - "â¤ï¸"
